language: php

php:
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - composer check-cs
  - composer test

notifications:
  on_success: never
  on_failure: always
